# Generated by Django 3.0.2 on 2020-02-02 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='entry',
            field=models.TextField(),
        ),
    ]
